"""empty message

Revision ID: 0bf47df942b9
Revises: 
Create Date: 2019-12-09 10:52:22.706000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0bf47df942b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('work_hours', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('start_date', mysql.DATETIME(), nullable=True),
    sa.Column('start_time', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('end_time', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('end_timsdje', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user', ['username'], unique=True)
    # ### end Alembic commands ###
