"""empty message

Revision ID: 11a126560e63
Revises: 17ba0ac51ce1
Create Date: 2019-12-09 13:12:28.874000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11a126560e63'
down_revision = '17ba0ac51ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('work_hours', sa.String(length=200), nullable=True))
    op.drop_column('days', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('start_time', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('days', 'work_hours')
    # ### end Alembic commands ###
