"""empty message

Revision ID: 561889462dbe
Revises: 5fd95b9ae2d3
Create Date: 2019-12-19 13:28:02.101000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '561889462dbe'
down_revision = '5fd95b9ae2d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('start_date', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
