"""empty message

Revision ID: 5fd95b9ae2d3
Revises: 
Create Date: 2019-12-19 12:24:55.558000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fd95b9ae2d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'end_time')
    op.drop_column('user', 'work_hours')
    op.drop_column('user', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('start_time', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=True))
    op.add_column('user', sa.Column('work_hours', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=True))
    op.add_column('user', sa.Column('end_time', mysql.VARCHAR(collation='utf8_unicode_ci', length=200), nullable=True))
    # ### end Alembic commands ###
